### ISSUE TITLE
Different indications for bling subsystem during different periods of the match

### ISSUE THREAD

**Issue by KyleRAnderson** [FRC2706/2017-2706-Robot-Code#23]
It would be nice for there to be different indications given by the bling subsystem during the match. Included:

- [x] During autonomous, flashy lights and fun patterns are displayed
- [x] During teleop, different patterns of lights would appear depending on what is happening. 
- [x] At the end of the match, somesort of light pattern would appear to indicate the end of the match.

**Comment by kevlam2706** [comment]
I would do this providing an API in the Bling subsystem to present different patterns. Here are some examples that I made up:

```
Bling.showColorFlash(Color.PURPLE); // flash purple
Bling.showEndOfMatchPattern(); // called at the end of the match
Bling.showDistanceIndicator(0.7); // show 70% on a distance indicator
Bling.showAngleIndicator(0.0); // show 0.0 (straight ahead) on an angle indicator
Bling.indicateReadyToReceiveGear(true); // tell human player we're ready
Bling.indicateReadyToReceiveGear(false); // tell human player we're not ready
```

I made those up, but you can come up with a list of useful functions based on what we know the Bling needs to do.

Each of those methods would correspond to a string command you would then send to the Arduino. 

Then, using the Command framework, we can call one of those functions inside of a robot Command or Command Group along with other subsystem commands. Suppose a Joystick button took care of automatically getting in position to get a gear. It could cause the following command sequence to execute:

```
bling.indicateReadyToReceiveGear(false);
gearHandler.closeGripper();
driveTrain.driveToDistanceFromWall(14); // 14 inches is the magic number
bling.indicateReadyToReceiveGear(true);
```
That's a bit over simplified, but that is the intent of how commands and command groups work.

**Comment by KyleRAnderson** [comment]
@greyingjay I was wondering if it would be okay to just use a simple `display` command to show different patterns and colours. The parameters for the command would determine if it would flash, what colours, etc.

**Comment by kevlam2706** [comment]
You could. It's good software design practice to ensure the subsytems are as independent as possible. For example, inside a "Get The Gear" command you could write this:

`bling.indicateReadyToReceiveGear(); // signal the predefined pattern`

and then have, inside the Bling subsystem class:

```
public void indicateReadyToReceiveGear() {
   // signal flashing green at full brightness
   display(0, 255, 0, true, 100, 5); // R, G, B, flashMode, brightness, numberOfCycles
}
```

Or you could write, let's say,

```
// signal that we're ready to receive the gear by flashing green
bling.display(0, 255, 0, true, 100, 5); // R, G, B, flashMode, brightness, numberOfCycles
```

Either one would work, but the difference is where you keep the knowledge about how the signals work. What exactly is the signal that we're ready to receive the gear? Who defined it? In the first example, it's the author of the Bling subsystem. In the second example, it's the author of the calling function.

Neither is right or wrong, but I like the first way, for a few reasons:

- it would keep all the patterns and displays in the same place (inside the Bling subsystem class) so you don't need to search the entire code to find them or change them
- if we decide to change or tweak the signal (make it a different color, change the flash pattern) do I need to change it in every command that calls Bling.display()? Or just one place inside indicateReadyToReceiveGear()?
- suppose we decided to change to some completely different signalling method, like showing a JPEG on an LCD display instead of using LED lights. With the first method, we could just change what indicateReadyToReceiveGear() does, and you're done.
- it makes the code easier to read and understand because whoever is writing the commands doesn't need to know in detail how the Bling subsystem works.

So I recommend you have both. Have a few functions that send predefined signals for things we know we need to display in a well-defined way. And also have a display() function that allows you to show different patterns or colors using the parameters, like you suggest.

**A good rule of thumb**: how often does this exact signal need to be done? If just once, let the user call the display() method to do it. If we're using it more than once, put it in a signal function so we can keep it in one place and call that function multiple times.

**Comment by KyleRAnderson** [comment]
This is done. Could add more signals but that might just get confusing.
