### ISSUE TITLE
Bling LED lights show weird patterns

### ISSUE THREAD

**Issue by KyleRAnderson** [FRC2706/2017-2706-Robot-Code#59]
The bling LED lights have been observed to show weird patterns of lights during practice. This is believed because of it being spammed, however a definite cause has yet to be found.

**Comment by kevlam2706** [comment]
If we don't have time to debug this for Toronto, the next best thing we can do is just tell the bling to turn on some nice patterns at the beginning of each mode (show something in auto, show something in teleop) and leave it.  For example, show a nice purple glow. We can do more debugging for Barrie.

**Comment by ounsworth** [comment]
I second Kevin, now is not the time for fiddling.

The drive team had asked that no more changes be made to the teleop software after Saturday afternoon. The reason is that after 8 hours of drive practice, they are used to it being a certain way, and if we change stuff, we will just make it more confusing because things will be different for the drivers.

I know you are trying to make improvements, but I would ask that you leave the bling code the way it was at the end of yesterday's drive practice, and keep it that way for Ryerson. You will get another chance to make changes for Barrie when there are more drive practices, and the drivers have time to get used to something new.

**Comment by kevlam2706** [comment]
Kyle, to plus on Mike's comments - we are both very impressed by your enthusiasm and your ideas. You are welcome to come to KRP tonight and test your bling code on Plyboy and work on fixing these bugs. Just please understand that your "development" code will not be able to become "production" code until after Toronto. Like in the real world, deploying "production" code requires a lot of testing first. In this case, the testing isn't just making sure there are no bugs, but that the people using the code are used to it.

Hopefully after experiencing the game for real you will also have better ideas about signals and decorative bling elements that we can have in Barrie.

I have ideas for bling signals to add to autonomous modes, to tell us what the robot is thinking. This is also something we can look at between now and Barrie.

**Comment by KyleRAnderson** [comment]
I guess, but I don't think I would be changing a lot - it may already be fixed, I think it's a problem with how other subsystems are spamming it. As it stands now, the signals on the bling are somewhat confusing with this bug and I don't want to confuse the drivers, so if I can't make it work I could do as you say and just make it show random fun patterns.

**Comment by ounsworth** [comment]
Kyle, let's talk about this tonight.

It's not that we're worried about code changes, or that we're worried about the bling patters being too distracting (what you had at the end of yesterday is fine for that). I'm sure it is will be an easy code fix once you find it, and I'm sure it will make the bling give more useful information.

The problem is that the drivers got used to the robot looking a certain way. Driving the robot at competition is very stressful - the drivers have a lot to think about. If the bling keeps changing how it looks / what the patterns mean every time they drive it, it's just going to add to the number of things they need to think about, and leave them less brain-power for actually driving. (The science term for this is "cognitive load").

As Kevin said, part of testing is giving people time to get used to the changes, so I'm asking that you leave bling the way it was at the end of yesterday.

Definitely go ahead and debug the bling code on Plyboy, and we may find a chance to get it on and get the drivers used to it before Ryerson. But be prepared that we may not. As Kevin said, no matter what you have the bling do for Ryerson, you will un-doubtedly get new ideas for things to change for Barrie.

That was a long post. Let's talk tonight in person.

**Comment by KyleRAnderson** [comment]
This issue is pretty much all fixed, but I won't close it yet.

**Comment by ounsworth** [comment]
Thanks for understanding Kyle. Hopefully at Drive practice tomorrow we have time to deploy and explain the bring to the whole drive team.
